0092

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -25,6 +25,17 @@ phases:
           --query 'Instances[0].InstanceId' \
           --output text
         )
+        if [ -z "$INSTANCE_ID" ]; then
+          echo "Failed to create EC2 instance. Exiting..."
+          exit 1
+        fi
+
+        echo "EC2 instance with ID $INSTANCE_ID created successfully."
+
+        echo "Waiting for the instance to be in 'running' state..."
+        aws ec2 wait instance-running --region $AWS_REGION --instance-ids $INSTANCE_ID
+        aws ec2 create-image --instance-id $INSTANCE_ID --name "prj-image" --no-reboot
+
   post_build:  # Phase for post-build actions (optional).
     commands:
       - echo nothing in post build.  # Placeholder command, you can add post-build actions here.
